@startuml
skinparam state {
  FontName "Noto Sans CJK TC Medium"
  FontSize 14
}

skinparam arrow {
  FontName "Noto Sans CJK TC Light"
  FontSize 11
}

state 未啟動 {
}

state 暫停 {
}

state 淡入 {
}

state 顯示 {
}

state 淡出 {
}

[*] -right-> 未啟動
未啟動 -up-> 暫停 : **滑鼠懸停** \n / 記錄滑鼠位置 \n 開始計時
暫停 --> 未啟動  : **滑鼠離開** \n 清除計時器
暫停 -up-> 淡入 : **時間到** \n /在滑鼠位置建立工具提示 \n 啟動計時器
暫停 --> 暫停 : **滑鼠移動** \n / 記錄滑鼠位置 \n 重設計時器
淡入 --> 淡入 : **計時器** \n / 遞增不透明度 \n 如果透明度已經到極限 \n 停止計時器 \n 啟動計時器
淡入 --> 淡入 : **滑鼠移動** \n 移動工具提示至游標處
淡入 --> 顯示
淡入 --> 淡出 : **滑鼠離開**
顯示 -right-> 顯示 : **滑鼠移動** \n 移動工具提示至游標處
顯示 --> 淡出 : **時間到，滑鼠離開** \n 啟動計時器
顯示 --> 淡出 : **滑鼠離開**
淡出 --> 淡出 : **計時器** \n / 遞減不透明度 \n 如果透明度已經到0 \n 停止計時器 \n 刪除工具提示
淡出 --> 未啟動
淡出 --> 淡入 : **滑鼠懸停**
淡出 --> 淡出 : **滑鼠移動，滑鼠離開** \n 移動工具提示至游標處

@enduml